orm_abc/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('orm_abc_app/', include('orm_abc_app.urls')),
    path('', include('orm_abc_app.urls')),
]

orm_abc_app/urls.py
from django.urls import path

from . import views

app_name = 'orm_abc_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('datetime_nov/', views.datetime_nov, name='datetime_nov'),
    path('var_list_dict/', views.var_list_dict, name='var_list_dict'),
    path('abc_form/', views.abc_form, name='abc_form'),
    path('abc_get/', views.abc_get, name='abc_get'),
    path('abc_model_form/', views.abc_model_form, name='abc_model_form'),
    path('abc_tweaks_form/', views.abc_tweaks_form, name='abc_tweaks_form'),
    path('abc_result/', views.abc_result, name='abc_result'),
    path('table/', views.table, name='table'),
]

orm_abc_app/models.py
# import datetime
from django.db import models

c_choices = (
    (0, "ноль"),
    (10, "десять"),
    (15, "пятнадцать"),
    (20, "двадцать"),
)


class AbcModel(models.Model):
    task = models.CharField(
        verbose_name="Формулировка  задачи",
        default="Равна ли С сумме A и B ?",
        max_length=255,
    )
    a = models.IntegerField(
        verbose_name="Значение А",
        default=0,
    )
    b = models.IntegerField(
        verbose_name="Значение B", default=2, help_text="Подсказка для значения B"
    )
    c = models.IntegerField(
        verbose_name="Значение С",
        choices=c_choices,
        default=10,
    )
    result = models.CharField(
        verbose_name="Результат",
        default="Результат не определен",
        max_length=255,
    )
    current_date = models.DateTimeField(
        verbose_name="Дата изменения(save)", auto_now=True
    )

    def __str__(self):
        # return self.task
        # return '%s %s' % (self.task, self.current_date)
        return f"self.id:{self.id}; self.task:{self.task}"

    class Meta:
        verbose_name = "A_B_C_Таблица"
        verbose_name_plural = "A_B_C_Таблицы"
        ordering = ("-pk", )


# current_date = models.DateTimeField("ДатаВремя", default=datetime.datetime.now())
# current_date = models.DateTimeField("ДатаВремя", auto_now_add=True)

# python manage.py makemigrations
# python manage.py migrate

# admin.py
# from django.contrib import admin
# # Register your models here.
# from .models import Abc
# admin.site.register(Abc)


# forms.py
# from django.forms import ModelForm
# from .models import Abc
#
# class CreateAbcForm(ModelForm):
#     class Meta:
#         model = Abc
#         fields = ['task', 'a' ,'b' ,'c', 'c_calc']

orm_abc_app/forms.py
# from django.forms import ModelForm
from django import forms
from django.forms import ModelForm
from .models import AbcModel


class AbcForm(forms.Form):
    task = forms.CharField(initial = "Равна ли С сумме A и B ?")
    a = forms.IntegerField(initial=1, min_value=0)
    b = forms.IntegerField(initial=1,required=False)
    c = forms.IntegerField(initial=1, label="c_lable")


class AbcModelForm(ModelForm):
    # task = forms.CharField(widget=forms.Textarea({'cols': '60', 'rows': "3"}))
    # task.widget.attrs.update({'cols': '40', 'rows': "2"})
    class Meta:
        model = AbcModel
        fields = '__all__'
        # fields = ['task', 'a', 'b','c']
        print('\nfields: ', fields)

orm_abc_app/views.py
import datetime,math
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.db.models import Count, Avg, Min, Max, StdDev, Sum
from .forms import AbcForm, AbcModelForm
from .models import AbcModel


def index(request):
    return render(request, "index.html")


def datetime_nov(request):
    datetime_now = datetime.datetime.now()
    print(datetime_now)
    context = {"key": datetime_now}
    return render(request, "datetime_now.html", context)


def var_list_dict(request):
    var_main = 2
    print(var_main)
    list_main = [1, 2, 3, 4, 5]
    print(list_main)
    dict_main = {"x": 1, "y": 2}
    print(dict_main)
    context = {"var_main": var_main, "list_main": list_main, "dict_main": dict_main}
    return render(request, "list_dict.html", context)





def abc_form(request):
    abc_form = AbcForm()
    print(abc_form)
    return render(request, "abc_form.html", {"abc_form": abc_form})


def abc_get(request):
    print(request.GET)
    task_value = (request.GET.get("task"))
    a_value = int(request.GET.get("a"))
    b_value =int(request.GET.get("b")) 
    c_value = int(request.GET.get("c")) 
    print (a_value, b_value, c_value)
    new_obj = AbcModel(task=task_value, a=a_value, b=b_value, c = c_value)
    new_obj.save()
    return redirect("orm_abc_app:abc_result")



def abc_model_form(request):
    print("request.method: ", request.method)
    if request.method == "POST":
        form = AbcModelForm(request.POST)
        if form.is_valid():
            print("\nform_is_valid:\n", form)
            form.save()
            return redirect("orm_abc_app:abc_result")
    else:
        form = AbcModelForm()
        print("\nform_else:\n", form)
    context = {"form": form}
    print("\ncontext:\n", context)
    return render(request, "abc_model_form.html", context)


def abc_tweaks_form(request):
    print("request.method: ", request.method)
    if request.method == "POST":
        form = AbcModelForm(request.POST)
        if form.is_valid():
            print("\nform_is_valid:\n", form)
            form.save()
            return redirect("orm_abc_app:abc_result")
    else:
        form = AbcModelForm()
        print("\nform_else:\n", form)
    context = {"form": form}
    print("\ncontext:\n", context)
    return render(request, "abc_tweaks_form.html", context)


def solution(a, b, c):
    if a + b == c:
        result = " С равна сумме A и B"
    else:
        result = "С не равна сумме A и B"
    return result


def abc_result(request):
    object_list = AbcModel.objects.all().order_by("-id")
    print("\n\nobject_list: ", object_list)

    last_object = object_list.values("task", "a", "b", "c")[0]
    print("\n\nlast_object: ", last_object)
    task_formulation = object_list.values("task")[0]
    task_id = object_list.values("id")[0]["id"]
    print("task_id task_formulation: ", task_id, task_formulation)


    result = solution(last_object["a"], last_object["b"], last_object["c"])
    print("\nresult: ", result)
  
    
    
    update_obj = AbcModel.objects.filter(id=task_id)
    update_result = result
    update_obj.update(result = update_result )

    # list
    values_list = object_list.values_list()[0]
    print("\nvalues_list: ", values_list)
    task_formulation = values_list[1]
    print("\ntask_formulation: ", task_formulation)
    last_values = [values_list[1], values_list[2], values_list[3], values_list[4]]
    print("\nlast_values:", last_values)


    context = {
        "last_object": last_object,
        "task_formulation": task_formulation,
        "last_values": last_values,
        "result": result,
    }
    return render(request, "abc_result.html", context)


def table(request):
    # all = AbcModel.objects.all()
    # all.delete()
    # objects_list
    objects_values = AbcModel.objects.values()
    print("\nobjects_values:", objects_values)
    # values_list
    objects_values_list = (
        AbcModel.objects.values_list().filter(id__gte=2).order_by("-id")
    )  # [0:3]
    print("\nobjects_values_list:", objects_values_list)
    cur_objects = objects_values_list
    statics_val = [
        cur_objects.aggregate(Count("b")),
        cur_objects.aggregate(Avg("b")),
        cur_objects.aggregate(Min("b")),
        cur_objects.aggregate(Max("b")),
        cur_objects.aggregate(StdDev("b")),
        cur_objects.aggregate(Sum("b")),
    ]
    print("\nstatics_val:", statics_val)
    statics = {"statics_val": statics_val}
    # fields_name
    fields = AbcModel._meta.get_fields()
    print("\nfields", fields)
    verbose_name_list = []
    name_list = []
    for e in fields:
        verbose_name_list.append(e.verbose_name)
        name_list.append(e.name)
    print("\nverbose_name_list:", verbose_name_list)
    print("\nname_list", name_list)
    field_names = verbose_name_list
    context = {
        "objects_values": objects_values,
        "name_list": name_list,
        "objects_values_list": objects_values_list,
        "verbose_name_list": verbose_name_list,
        "statics": statics,
        "field_names": field_names,
    }
    return render(request, "table.html", context)

orm_abc_app/templates/abc_form.html
{% extends 'layout.html' %}

{% block title %} form_abc_app/abc_form {% endblock %}

{% block content %}
    <h5>orm_abc_app:abc_form</h5>
    <pre>
    https://docs.djangoproject.com/en/4.1/ref/forms/
    </pre>
    {% comment %} <form action="../views.py/abc_get" metod='get' target="_self"> {% endcomment %}
    <form action="{% url 'orm_abc_app:abc_get' %}" metod='get' target="_self">
        {{ abc_form }}
        <label for="id_submit">&nbsp;</label>
        <button type="submit" id="id_submit">Отправить</button>
        </label>
    </form>
{% endblock %}

orm_abc_app/templates/abc_model_form.html
{% extends 'layout.html' %}

{% block title %} form_abc_app/form_create_0 {% endblock %}

{% block content %}
    <h5>orm_abc_app:abc_model_form</h5>
    <form action= "{% url 'orm_abc_app:abc_model_form' %}"" method="POST">
        {% csrf_token %}
        {{ form }}
        <label for="id_submit">&nbsp;</label>
        <button type="submit" id="id_submit">Отправить</button>
        </label>
    </form>
{% endblock %}

orm_abc_app/templates/abc_result.html
{% extends 'layout.html' %}

{% block title %}orm_abc_app:result{% endblock %}

{% block content %}
    <h5>orm_abc_app:result</h5>
    <h6>{{ task_formulation }}</h6>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">Задача</th>
            <th scope="col">A</th>
            <th scope="col">B</th>
            <th scope="col">C</th>
            <th scope="col">Результат</th>
        </tr>
        </thead>
        <tbody style="border-top: 0px;">

        <tr>
            {% for key, value in last_object.items %}
                <td>{{ key }}:{{ value }}</td>
            {% endfor %}
            <td>{{ result }}</td>
        </tr>

        <tr>
            {% for item in last_values %}
                <td>{{ item }}</td>
            {% endfor %}
            <td>{{ result }}</td>
        </tr>

        </tbody>
    </table>
{% endblock %}

orm_abc_app/templates/abc_tweaks_form.html
{% extends 'layout.html' %}

{% block title %} form_abc_app:abc_tweaks_form {% endblock %}

{% block content %}
    <h5>orm_abc_app:abc_tweaks_form</h5>
    {% load widget_tweaks %}
    <form {% url 'orm_abc_app:abc_tweaks_form' %} method="POST">
        {% csrf_token %}
        {% comment %} {% render_field form.task %} {% endcomment %}
        <div class="form-group mb-1">
            <div class="mb-1 row">
                <label class="col-sm-2 col-form-label">Формулировка</label>
                <div class="col-sm-10">
                    {% render_field form.task class="form-control" %}
                </div>
            </div>

            <div class="mb-1 row">
                <label class="col-sm-2 col-form-label">A</label>
                <div class="col-sm-10">
                    {% render_field form.a class="form-control" %}
                </div>
            </div>

            <div class="mb-1 row">
                <label class="col-sm-2 col-form-label">B</label>
                <div class="col-sm-10">
                    {% render_field form.b class="form-control" %}
                </div>
            </div>

            <div class="mb-1 row">
                <label class="col-sm-2 col-form-label">C</label>
                <div class="col-sm-10">
                    {% render_field form.c class="form-control" %}
                </div>
            </div>

            <div class="mb-1 row">
                <label class="col-sm-2 col-form-label">Результат</label>
                <div class="col-sm-10">
                    {% render_field form.result class="form-control" %}
                </div>
            </div>


            <div class="mb-1 row">
                <label class="col-sm-8 col-form-label"></label>
                <div class="col-sm-4 text-end">
                    <button type="submit" class="form-control">Отправить</button>
                </div>
            </div>
        </div>

    </form>
{% endblock %}

orm_abc_app/templates/datetime_now.html
{% extends 'layout.html' %}

{% block title %}
    orm_abc_app: date_time
{% endblock %}

{% block content %}
    <h5>orm_abc_app:date_time-content</h5>
    datetime_now: {{ key }}
{% endblock %}

orm_abc_app/templates/form_create.html
{% extends 'layout.html' %}

{% block title %} form_abc_app:form_create {% endblock %}

{% block content %}
    <h5>orm_abc_app:form_create</h5>
    {% load widget_tweaks %}
    <form {% url 'orm_abc_app:form_create' %} method="POST">
        {% csrf_token %}
        <div class="form-group mb-1">
            <div class="mb-1 row">
                <label class="col-sm-2 col-form-label">Формулировка</label>
                <div class="col-sm-10">
                    {% render_field form.task class="form-control" %}
                </div>
            </div>

            <div class="mb-1 row">
                <label class="col-sm-2 col-form-label">A</label>
                <div class="col-sm-10">
                    {% render_field form.a class="form-control" %}
                </div>
            </div>

            <div class="mb-1 row">
                <label class="col-sm-2 col-form-label">B</label>
                <div class="col-sm-10">
                    {% render_field form.b class="form-control" %}
                </div>
            </div>

            <div class="mb-1 row">
                <label class="col-sm-2 col-form-label">C</label>
                <div class="col-sm-10">
                    {% render_field form.c class="form-control" %}
                </div>
            </div>


            <div class="mb-1 row">
                <label class="col-sm-8 col-form-label"></label>
                <div class="col-sm-4 text-end">
                    <button type="submit" class="form-control">Отправить</button>
                </div>
            </div>
        </div>

    </form>
{% endblock %}

orm_abc_app/templates/form_create_0.html
{% extends 'layout.html' %}

{% block title %} form_abc_app/form_create_0 {% endblock %}

{% block content %}
    <h5>orm_abc_app:form_create_0</h5>
    <pre>
    https://docs.djangoproject.com/en/4.1/ref/forms/
    </pre>
    <form {% url 'orm_abc_app:form_create_0' %} method="POST">
        {% csrf_token %}
        {{ form }}
        <label for="id_submit">&nbsp;</label>
        <button type="submit" id="id_submit">Отправить</button>
        </label>
    </form>
{% endblock %}

orm_abc_app/templates/index.html
{% extends 'layout.html' %}

{% block title %}
    orm_abc_app:index-title
{% endblock %}

{% block content %}
    <h5>orm_abc_app:index-content</h5>
    <pre>
    https://docs.djangoproject.com/en/5.0/ref/models/querysets/
    </pre>
    <pre>  
    https://docs.djangoproject.com/en/4.1/ref/templates/
    https://docs.djangoproject.com/en/4.1/ref/templates/language/#variables
    https://docs.djangoproject.com/en/4.1/ref/templates/language/#tags
    </pre>
    <pre>
    https://docs.djangoproject.com/en/4.1/contents/
    https://docs.djangoproject.com/en/4.1/ref/models/
    https://docs.djangoproject.com/en/4.1/ref/models/fields/
    https://docs.djangoproject.com/en/4.1/ref/models/options/
    https://docs.djangoproject.com/en/4.1/ref/models/querysets/
    https://docs.djangoproject.com/en/4.1/ref/models/expressions/
    https://docs.djangoproject.com/en/4.1/ref/models/conditional-expressions/#advanced-queries
    https://docs.djangoproject.com/en/4.1/ref/models/database-functions/
    https://docs.djangoproject.com/en/5.0/ref/models/querysets/#filter
    </pre>
    <pre>
     http://127.0.0.1:8000/admin/    root root
    </pre>
{% endblock %}

orm_abc_app/templates/layout.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% load static %}
    <link href="{% static 'css/mycss.css' %}" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
</head>

<div class="container">

    <div class="card">
        <div class="card-body bgc">
            {% load static %} <img src="{% static 'images/settings_django.png' %}"
                                   alt="settings_django" height="30px">
            <p>
            <pre>object-relational mapper</pre>
            </p>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            {% include "navigation.html" %}
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            {% block content %}{% endblock %}
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            Footer
        </div>
    </div>

</div>

<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
</html>

orm_abc_app/templates/list_dict.html
{% extends 'layout.html' %}

{% block title %}orm_abc_app:var_list_dict{% endblock %}


{% block content %}
    <h5>var_list_dict</h5>
    <p> var_main: {{ var_main }}</p>
    <p>list_main: {{ list_main }}</p>
    <p>list_main.1: {{ list_main.1 }}</p>
    <ul>
        {% for value in list_main %}
            {% if  value == var_main %}
                <li>true: {{ value }}
                    {% else %}
                <li>else: {{ value }}
            {% endif %}
        {% endfor %}
    </ul>

    <p>dict_main</p>
    <ul>
        <li>{{ dict_main }}
        <li>{{ dict_main.x }}
        <li>{{ dict_main.y }}
            <ul>
                {% for key, value in dict_main.items %}
                    <li>{{ key }}: {{ value }}
                    {% if value == var_main %} - true_value
                    {% else %} - false_value
                    {% endif %}
                {% endfor %}
            </ul>
    </ul>
{% endblock %}

orm_abc_app/templates/navigation.html
<ul class="nav">
    <li class="nav-item"><a class="nav-link" href="{% url 'orm_abc_app:index' %}">orm_abc_app:index</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'orm_abc_app:datetime_nov' %}">orm_abc_app:datetime_nov</a>
    <li class="nav-item"><a class="nav-link" href="{% url 'orm_abc_app:var_list_dict' %}">orm_abc_app:var_list_dict</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'orm_abc_app:abc_form' %}">orm_abc_app:abc_form</a></li>
    {% comment %} <li class="nav-item"><a class="nav-link" href="{% url 'orm_abc_app:abc_get' %}">orm_abc_app:abc_get</a></li> {% endcomment %}
    <li class="nav-item"><a class="nav-link" href="{% url 'orm_abc_app:abc_model_form' %}">orm_abc_app:abc_model_form</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'orm_abc_app:abc_tweaks_form' %}">orm_abc_app:abc_tweaks_form</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'orm_abc_app:abc_result' %}">orm_abc_app:abc_result</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'orm_abc_app:table' %}">orm_abc_app:table</a></li>
</ul>

orm_abc_app/templates/table.html
{% extends 'layout.html' %}

{% block title %}orm_abc_app:table{% endblock %}


{% block content %}
    <h5>orm_abc_app:table</h5>
    <h6>Таблица по-умолчанию</h6>
    <table class="table table-bordered">
        <tbody style="border-top: 3.0px;">
        <tr>
            {% for name in name_list %}
                <td>{{ name }}</td>
            {% endfor %}
        </tr>
        {% for object in objects_values %}
            <tr>
                {% for key, value in object.items %}
                    <td>
                        {{ value }}
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}
        <tbody>
    </table>

    <h6>Таблица после фильтрации и сортировки</h6>
    <table class="table table-bordered">
        <tbody style="border-top: 3.0px;">
        <tr>
            {% for name in verbose_name_list %}
                <td>{{ name }}</td>
            {% endfor %}
        </tr>
        {% for objects_values in objects_values_list %}
            <tr>
                {% for item in objects_values %}
                    <td>
                        {{ item }}
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}
        <tbody>
    </table>

    <p>Статистика после фильтрации и сортировки </p>
    {#    {% autoescape off %}{{ statics.statics_val }}{% endautoescape %}#}
    {% for item in statics.statics_val %}
        {% for k, v in  item.items %}
            {{ k }}:  {{ v }};
            {#            {% autoescape off %}{{ k }}:  {{ v }}; {% endautoescape %}#}
        {% endfor %}
    {% endfor %}


{% endblock %}